# Generated by Django 3.1.7 on 2021-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='guestbook_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
