# Generated by Django 3.1.7 on 2021-03-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='guestbook_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
