# Generated by Django 3.1.7 on 2021-03-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210323_1012'),
        ('articles', '0002_auto_20210323_0618'),
    ]

    operations = [
    ]
