# Generated by Django 3.1.7 on 2021-03-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_merge_20210323_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
