# Generated by Django 3.1.7 on 2021-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('art_image', models.CharField(max_length=50)),
                ('art_description', models.CharField(max_length=50)),
                ('art_voice_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('input_image_1', models.CharField(max_length=100)),
                ('input_image_2', models.CharField(max_length=100)),
                ('input_image_3', models.CharField(max_length=100)),
                ('input_image_4', models.CharField(max_length=100)),
                ('output_image_1', models.CharField(max_length=100)),
                ('output_image_2', models.CharField(max_length=100)),
                ('output_image_3', models.CharField(max_length=100)),
                ('output_image_4', models.CharField(max_length=100)),
            ],
        ),
    ]
