# Generated by Django 3.1.7 on 2021-03-26 12:39

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='session_id',
            new_name='sessionkey',
        ),
        migrations.AlterField(
            model_name='card',
            name='input_image_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='input'),
        ),
        migrations.AlterField(
            model_name='card',
            name='input_image_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='input'),
        ),
        migrations.AlterField(
            model_name='card',
            name='input_image_3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='input'),
        ),
        migrations.AlterField(
            model_name='card',
            name='input_image_4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='input'),
        ),
        migrations.AlterField(
            model_name='card',
            name='output_image_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='output'),
        ),
        migrations.AlterField(
            model_name='card',
            name='output_image_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='output'),
        ),
        migrations.AlterField(
            model_name='card',
            name='output_image_3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='output'),
        ),
        migrations.AlterField(
            model_name='card',
            name='output_image_4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='output'),
        ),
    ]
